# Generated by Django 3.2.5 on 2023-06-11 14:31

import datetime
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_area_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gouvernorat', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('code_postal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Area_Of_Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_competence_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/candidate_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('grantor', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buisness_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='static/logos/')),
                ('phone_number', models.CharField(max_length=20)),
                ('activity_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.activityarea')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.address')),
            ],
        ),
        migrations.CreateModel(
            name='Degree_Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_degreeF', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Degree_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_degreeT', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_diploma', models.CharField(max_length=255, null=True)),
                ('code', models.ImageField(blank=True, null=True, upload_to='static/qr_code/')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_description', models.TextField(blank=True, null=True)),
                ('experience_date_deb', models.DateField(blank=True, null=True)),
                ('experience_date_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Ins', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Availibility', models.CharField(choices=[('--Please select availability--', '--Please select availability--'), ('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Remote', 'Remote')], default='', max_length=255)),
                ('min_salary', models.IntegerField(default=0)),
                ('max_salary', models.IntegerField(default=0)),
                ('Experience', models.CharField(choices=[('No experience required', 'No experience required'), ('Less than 1 year', 'Less than 1 year'), ('1-2 years', '1-2 years'), ('2-5 years', '2-5 years'), ('5-10 years', '5-10 years'), ('10+ years', '10+ years')], default='', max_length=255)),
                ('job_description', models.TextField(default='', validators=[django.core.validators.MinLengthValidator(200)])),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('area_of_competence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentification.area_of_competence')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='authentification.company')),
                ('diploma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentification.diploma')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Size_Of_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User1',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('role', models.CharField(max_length=20)),
                ('situation', models.CharField(blank=True, max_length=50, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('signed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='authentification.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='authentification.candidate')),
                ('degree_fields', models.ManyToManyField(blank=True, null=True, related_name='participations', to='authentification.Degree_Fields')),
                ('diploma', models.ManyToManyField(blank=True, null=True, related_name='participations', to='authentification.Diploma')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='authentification.job')),
                ('skills', models.ManyToManyField(blank=True, null=True, related_name='participations', to='authentification.Skills')),
            ],
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('degree_fields', models.ManyToManyField(blank=True, to='authentification.Degree_Fields')),
                ('degree_type', models.ManyToManyField(blank=True, to='authentification.Degree_Types')),
                ('diploma', models.ManyToManyField(blank=True, to='authentification.Diploma')),
                ('nom_fac', models.ManyToManyField(blank=True, to='authentification.Institution')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentification.jobposition'),
        ),
        migrations.AddField(
            model_name='job',
            name='skill_required',
            field=models.ManyToManyField(to='authentification.Skills'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='authentification.candidate')),
                ('experience', models.ManyToManyField(blank=True, to='authentification.Experience')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='size_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.size_of_company'),
        ),
        migrations.AddField(
            model_name='company',
            name='user_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companys', to='authentification.user1'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='certificates',
            field=models.ManyToManyField(blank=True, to='authentification.Certificate'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='interests',
            field=models.ManyToManyField(blank=True, to='authentification.Interests'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='languages',
            field=models.ManyToManyField(blank=True, to='authentification.Language'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parcours',
            field=models.ManyToManyField(blank=True, to='authentification.Parcours'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(to='authentification.Skills'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user_can',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='authentification.user1'),
        ),
    ]
