# Generated by Django 3.2.5 on 2023-06-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='static/candidate_cvs/'),
        ),
    ]
