# Generated by Django 3.2.5 on 2023-06-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_participation_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='degree_fields',
            field=models.ManyToManyField(related_name='participations', to='authentification.Degree_Fields'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='diploma',
            field=models.ManyToManyField(related_name='participations', to='authentification.Diploma'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='skills',
            field=models.ManyToManyField(related_name='participations', to='authentification.Skills'),
        ),
    ]
