# Generated by Django 3.2.5 on 2023-06-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_auto_20230612_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Availibility',
            field=models.CharField(blank=True, choices=[('--Please select availability--', '--Please select availability--'), ('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Remote', 'Remote')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='Experience',
            field=models.CharField(blank=True, choices=[('No experience required', 'No experience required'), ('Less than 1 year', 'Less than 1 year'), ('1-2 years', '1-2 years'), ('2-5 years', '2-5 years'), ('5-10 years', '5-10 years'), ('10+ years', '10+ years')], default='', max_length=255, null=True),
        ),
    ]
